- defaultTab: nodes
  description: |-
        Repo: Yapo / data-sac/csat-quality-reviews
        This pipeline makes available data associated with customer service
        performed by the SAC and Quality team. From this data you can obtain information
        associated with number of customer moderations for different dimensions adding the information
        to a level where it balances the degree of aggregation with the specificity we need.
        This data is obtained through the interaction with various tables in our datawarehouse
        and and is recorded into datawarehouse after being transformed into this pipeline.
  executionEnabled: true
  group: SAC
  loglevel: DEBUG
  name: Csat-and-quality-reviews
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notification:
    onfailure:
      email:
        recipients: data_team@adevinta.com
        subject: ${job.execid} ${execution.status} ${job.name} - Fallo definitivo
    onretryablefailure:
      email:
        recipients: data_team@adevinta.com
        subject: ${job.execid} ${execution.status} ${job.name} - Fallo por reintento
  notifyAvgDurationThreshold: null
  scheduleEnabled: true
  schedule:
    month: '*'
    time:
      hour: '09'
      minute: '0'
      seconds: '0'
    weekday:
      day: '*'
    year: '*'
  retry:
    retry: 3
    delay: 20m
  sequence:
    commands:
    - script: |-
        sudo docker pull containers.mpi-internal.com/yapo/csat-quality-reviews:latest
        sudo docker run --rm -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -e APP_DW_SECRET=/app/db-secret \
                        containers.mpi-internal.com/yapo/csat-quality-reviews:latest
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago
