- defaultTab: nodes
  description: |-
        <Add a description about what this ETL does>
        sudo docker run -v /home/bnbiuser/secrets/pulse_auth:/app/pulse-secret \
                        -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -e APP_PULSE_SECRET=/app/pulse-secret \
                        -e APP_DB_SECRET=/app/db-secret \
                        containers.mpi-internal.com/yapo/csat-quality-reviews:[git-branch]
  executionEnabled: true
  group: DOCKER/<FOLDER RUNDECK LOCATION>
  loglevel: DEBUG
  name: <FOLDER RUNDECK LOCATION> - Project Name Template
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notifyAvgDurationThreshold: null
  scheduleEnabled: false
  sequence:
    commands:
    - script: |-
        sudo docker pull containers.mpi-internal.com/yapo/csat-quality-reviews:[git-branch]
        sudo docker run -v /home/bnbiuser/secrets/pulse_auth:/app/pulse-secret \
                        -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -e APP_PULSE_SECRET=/app/pulse-secret \
                        -e APP_DB_SECRET=/app/db-secret \
                        containers.mpi-internal.com/yapo/csat-quality-reviews:[git-branch]
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago
