- defaultTab: nodes
  description: |-
        https://github.mpi-internal.com/Yapo/data-sac/tree/master/implio-report
        sudo docker run --rm --net=host \
                    -v /home/bnbiuser/secrets/blocket_db:/app/db-blocket \
                    -e APP_BLOCKET_SECRET=/app/db-blocket \
                    containers.mpi-internal.com/yapo/implio_report:latest \
                    -email_from="noreply@yapo.cl -- if put this options replace default email from" \
                    -email_to="gp_data_analytics@yapo.cl,customer.care@yapo.cl"
  executionEnabled: true
  group: DOCKER/SAC
  loglevel: DEBUG
  name: SAC - Implio Report
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notification:
    onfailure:
      email:
        recipients: data_team@adevinta.com
        subject: ${job.execid} ${execution.status} ${job.name} - Fallo definitivo
      plugin:
        configuration:
          slack_channel: ''
          webhook_base_url: https://hooks.slack.com/services
          webhook_token: T017F9KHA1Y/B01BL7C1CSY/Ai9NzdCrBUA5Ru5sa8JHYrjR
        type: SlackNotification
  notifyAvgDurationThreshold: null
  schedule:
    month: '*'
    time:
      hour: '04'
      minute: '30'
      seconds: '0'
    weekday:
      day: '1'
    year: '*'
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        sudo docker pull containers.mpi-internal.com/yapo/implio_report:latest
        sudo docker run --rm --net=host \
                        -v /home/bnbiuser/secrets/blocket_db:/app/db-blocket \
                        -e APP_BLOCKET_SECRET=/app/db-blocket \
                        containers.mpi-internal.com/yapo/implio_report:latest \
                        -email_from="noreply@yapo.cl" \
                        -email_to="gp_data_analytics@yapo.cl,customer.care@yapo.cl"
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago