- defaultTab: nodes
  description: |-
        <Add specific URL or path of the pipeline in github>
        sudo docker run --rm --net=host \
                        -v /home/bnbiuser/secrets/pulse_auth:/app/pulse-secret \
                        -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -v /home/bnbiuser/secrets/smtp:/app/smtp-secret \
                        -e APP_PULSE_SECRET=/app/pulse-secret \
                        -e APP_DB_SECRET=/app/db-secret \
                        -e APP_SMTP_SECRET=/app/smtp-secret \
                        containers.mpi-internal.com/yapo/implio_report:[git-branch] \
                        -email_from="noreply@yapo.cl" \
                        -email_to="data_team@adevinta.com"
  executionEnabled: true
  group: DOCKER/<FOLDER RUNDECK LOCATION>
  loglevel: DEBUG
  name: <FOLDER RUNDECK LOCATION> - Project Name Template
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: dockerhost'
  nodesSelectedByDefault: true
  notifyAvgDurationThreshold: null
  scheduleEnabled: false
  sequence:
    commands:
    - script: |-
        sudo docker pull containers.mpi-internal.com/yapo/implio_report:[git-branch]
        sudo docker run --rm --net=host \
                        -v /home/bnbiuser/secrets/pulse_auth:/app/pulse-secret \
                        -v /home/bnbiuser/secrets/dw_db:/app/db-secret \
                        -v /home/bnbiuser/secrets/smtp:/app/smtp-secret \
                        -e APP_PULSE_SECRET=/app/pulse-secret \
                        -e APP_DB_SECRET=/app/db-secret \
                        -e APP_SMTP_SECRET=/app/smtp-secret \
                        containers.mpi-internal.com/yapo/implio_report:[git-branch] \
                        -email_from="noreply@yapo.cl" \
                        -email_to="data_team@adevinta.com"
    keepgoing: false
    strategy: node-first
  timeZone: America/Santiago